# Generated by Django 4.1 on 2022-08-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_img_confirm_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_confirm_purchased',
        ),
    ]
