# Generated by Django 4.1 on 2022-08-10 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=19, unique=True)),
                ('type', models.CharField(default='Trail', max_length=10)),
                ('state', models.CharField(default='Running', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('duration', models.IntegerField(default=14)),
                ('gen_date', models.DateTimeField(auto_now_add=True)),
                ('act_date', models.DateTimeField(blank=True, null=True)),
                ('last_check_date', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hddid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('sw_version', models.CharField(blank=True, max_length=20, null=True)),
                ('reactivation_counts', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
