# Generated by Django 4.1 on 2022-08-10 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_notification_header_gift_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gift_message',
            new_name='GiftMessage',
        ),
    ]
