# Generated by Django 4.1 on 2022-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_giftmessage_created_at_alter_giftmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='img',
            field=models.ImageField(default='', upload_to='images/purchased_confirmation'),
            preserve_default=False,
        ),
    ]
