# Generated by Django 4.1 on 2022-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_key_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='img_confirm_purchased',
            field=models.ImageField(blank=True, null=True, upload_to='images/confirmation/'),
        ),
    ]
