# Generated by Django 4.1 on 2022-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_key_img_confirm_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
