# Generated by Django 4.1 on 2022-08-10 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('activation_code', models.CharField(blank=True, max_length=8, null=True)),
                ('trys_num', models.IntegerField(default=0)),
                ('ban', models.BooleanField(default=False)),
                ('ban_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
